In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel('Análisis_de_piso.xlsx')
df.head()

,Unnamed: 0,Leads Piso 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,979,811,Unnamed: 45,Unnamed: 46,Factor minimo mejor vendedor,Factor minimo mejor vendedor .1,Unnamed: 49,Unnamed: 50
0,NaN,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
1,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0,1,5,1,0,1.00,5.00,1,20
3,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
4,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,1,0,0,0.00,0.00,NaN,NaN

In [8]:
df_sinnulos = df.isnull().sum()
df_sinnulos

Unnamed: 0                                1
Leads Piso 2024                          19
Unnamed: 2                               31
Unnamed: 3                               23
Unnamed: 4                               28
Unnamed: 5                               30
Unnamed: 6                               29
Unnamed: 7                               30
Unnamed: 8                               27
Unnamed: 9                               31
Unnamed: 10                              25
Unnamed: 11                              31
Leads Piso 2025                          30
Unnamed: 13                              30
Unnamed: 14                              33
Unnamed: 15                              31
Total                                     0
Total Ajustado                            0
Raking                                    2
Raking ajustado                           2
Ventas Piso 2024                          0
Unnamed: 21                              38
Unnamed: 22                              35
Unnamed: 23                              39
Unnamed: 24                              38
Unnamed: 25                              36
Unnamed: 26                              36
Unnamed: 27                              35
Unnamed: 28                              38
Unnamed: 29                              34
Unnamed: 30                              34
Unnamed: 31                              35
Ventas Piso 2025                         33
Unnamed: 33                              35
Unnamed: 34                               0
Unnamed: 35                              34
* se actualiza al reportar en Sale-U     38
Unnamed: 37                               1
Unnamed: 38                               1
Unnamed: 39                               1
263                                      15
Unnamed: 41                               1
Unnamed: 42                               1
979                                       1
811                                       2
Unnamed: 45                               3
Unnamed: 46                               2
Factor minimo mejor vendedor              1
Factor minimo mejor vendedor .1           1
Unnamed: 49                              18
Unnamed: 50                              15
dtype: int64

In [10]:
#Eliminar primera fila o filas innecesarias
df_sinnulos= pd.read_excel('Análisis_de_piso.xlsx', skiprows=1)
df_sinnulos

,Unnamed: 0,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
0,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0.00,1.0,5.0,1.00,0.00,1.00,5.00,1.0,20.0
2,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59.0,40.0,0.31,0.02,3.28,2.22,7.0,10.0
3,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0.00,1.0,1.0,0.00,0.00,0.00,0.00,NaN,NaN
4,AURELIO FELIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,...,11,0.38,28.0,31.0,0.29,0.01,3.50,3.88,9.0,18.0
5,CARLOS ALBERTO NIETO,NaN,NaN,NaN,2,NaN,NaN,2,8,4,...,8,0.60,64.0,30.0,0.23,0.02,4.27,2.00,13.0,7.0
6,CARLOS TEXIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,17,0.25,21.0,26.0,0.19,0.01,5.25,6.50,18.0,23.0
7,CARLOS MANUEL CARMONA,18,10,27,34,11,3,NaN,NaN,NaN,...,0,0.00,54.0,8.0,0.00,0.00,0.00,0.00,NaN,NaN
8,CINTYA,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,0,0.00,3.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
9,CLAUDIA GALVAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19,0.00,25.0,22.0,0.08,0.00,12.50,11.00,22.0,26.0
10,CASA,1,NaN,3,3,2,NaN,NaN,NaN,NaN,...,4,0.10,20.0,32.0,1.05,0.00,0.95,1.52,NaN,3.0
11,DANIEL DE LEON CANDIA,1,NaN,1,NaN,NaN,NaN,NaN,1,5,...,9,0.42,36.0,25.0,0.33,0.02,3.00,2.08,6.0,9.0
12,DAVID JIMENEZ,NaN,NaN,10,5,7,NaN,NaN,NaN,NaN,...,23,0.00,19.0,5.0,0.05,0.00,19.00,5.00,23.0,20.0
13,Demo Vendedor,2,2,2,NaN,NaN,3,NaN,NaN,NaN,...,-,0.00,7.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
14,GUADALUPE PEREZ,NaN,NaN,1,2,5,NaN,NaN,NaN,NaN,...,-,0.00,8.0,7.0,0.00,0.00,0.00,0.00,NaN,NaN
15,SEBASTIAN BENHUMEA,1,NaN,1,NaN,NaN,1,1,NaN,NaN,...,19,0.00,25.0,22.0,0.08,0.00,12.50,11.00,22.0,26.0
16,USUARIO DE BDC Y CASA,2,1,4,1,NaN,3,6,1,NaN,...,10,0.00,17.0,11.0,0.65,0.00,1.55,1.00,3.0,1.0
17,JAIME GONZALEZ,NaN,NaN,1,1,4,12,29,8,7,...,3,0.28,34.0,61.0,0.74,0.00,1.36,2.44,2.0,12.0
18,JESUS SERRANO,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19,1.00,18.0,6.0,0.11,0.17,9.00,3.00,20.0,15.0
19,JOSE CARLOS ZENTENO,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,...,23,1.00,5.0,2.0,0.20,0.50,5.00,2.00,17.0,7.0
20,JOSE EDUARDO PARADA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,4.0,8.0,0.00,0.00,0.00,0.00,NaN,NaN
21,JOSE MANUEL LOPEZ,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18,0.67,1.0,5.0,3.00,0.13,0.33,1.67,NaN,4.0
22,JOSE MANUEL LOPEZ,67,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,0.0,7.0,NaN,0.00,0.00,0.00,NaN,NaN
23,JOSETTE RAMON,NaN,NaN,NaN,2,5,17,5,9,NaN,...,7,0.38,48.0,49.0,0.33,0.01,3.00,3.06,6.0,16.0
24,LAURA LOPEZ,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,-,0.00,3.0,2.0,0.00,0.00,0.00,0.00,NaN,NaN
25,LIZBETH GOMEZ GONZALEZ,10,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,4.0,3.0,0.00,0.00,0.00,0.00,NaN,NaN
26,LUIS ALBERTO RODRIGUEZ,6,NaN,12,NaN,NaN,2,NaN,NaN,NaN,...,-,0.00,3.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
27,LUISA LBERTO GOMEZ,42,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,19,0.50,9.0,4.0,0.22,0.13,4.50,2.00,14.0,7.0
28,MARIA GUADALUPE PALACIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13,0.43,35.0,24.0,0.20,0.02,5.00,3.43,17.0,17.0
29,MAURICIO ALFREDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,0.50,29.0,42.0,0.28,0.01,3.63,5.25,10.0,21.0
30,MIGUEL ANGEL SONDEREGGER,37,NaN,4,36,21,37,25,16,8,...,2,0.64,117.0,66.0,0.24,0.01,4.18,2.36,12.0,11.0
31,MONICA GISELA FLORES,NaN,NaN,NaN,NaN,NaN,2,7,5,2,...,-,0.00,22.0,9.0,0.00,0.00,0.00,0.00,NaN,NaN
32,NANCY OLASCOAGA,1,NaN,NaN,NaN,NaN,NaN,NaN,2,5,...,14,0.00,48.0,55.0,0.13,0.00,8.00,9.17,19.0,24.0
33,NAYELI MONTES DEOCA,41,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0.00,4.0,3.0,0.25,0.00,4.00,3.00,11.0,15.0
34,OSCAR ALONSO,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,14,0.00,29.0,36.0,0.21,0.00,4.83,6.00,15.0,22.0
35,PAUL ROSAS IRIGOYIN,1,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,...,14,0.83,5.0,9.0,1.20,0.09,0.83,1.50,NaN,2.0
36,PAUL ROSAS,83,7,11,6,NaN,NaN,NaN,NaN,NaN,...,-,0.00,1.0,6.0,0.00,0.00,0.00,0.00,NaN,NaN
37,PEDRO GONZALES,2,NaN,11,17,7,19,11,5,2,...,1,0.39,123.0,75.0,0.29,0.01,3.42,2.08,8.0,9.0
38,RICARDO SILVA HERAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,3.0,2.0,0.00,0.00,0.00,0.00,NaN,NaN
39,sys_competition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,...,-,0.00,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
40,VICTOR MANUEL SANCHEZ ARROYO,4,3,NaN,1,2,NaN,NaN,2,NaN,...,4,0.14,46.0,57.0,0.46,0.00,2.19,2.71,4.0,13.0

In [13]:
df1 = pd.read_excel('Basee_de_Leads.xlsx')
df1.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Basee_de_Leads.xlsx'